urls.py
from django.conf.urls import url
from . import views

app_name = 'hospital'

urlpatterns = [
	# /hospital/
	url(r'^$', views.IndexView.as_view(), name='index'),

	# /hospital/71/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

models.py
from __future__ import unicode_literals

from django.db import models

class Item(models.Model):
	name = models.CharField(max_length=250)
	street = models.CharField(max_length=250)
	city = models.CharField(max_length=250)
	state = models.CharField(max_length=250)
	zipcode = models.IntegerField() 
	diagnosis_related_group = models.CharField(max_length=250)
	avg_covered_charges = models.FloatField()
	avg_total_payments = models.FloatField()
	avg_medicare_payments= models.FloatField()

	def __str__(self):
		return self.name
		
	

views.py
from django.views import generic
from .models import Item

class IndexView(generic.ListView):
	template_name = 'hospital/index.html'
	context_object_name = 'all_items'

	def get_queryset(self):
		return Item.objects.all()


class DetailView(generic.DetailView):
	model = Item
	template_name = 'hospital/detail.html'


	
	
		

templates/aboutus/aboutUs.html
{% extends 'hospital/base.html' %}
{% block body %}


<h1>The about us page</h1>


{% endblock %}

templates/hospital/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Echosort</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'hospital/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="containter-fluid">

	<!-- header -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="{% url 'hospital:index' %}">Echosort</a>
	</div>

	<!-- Items -->
	<div class="collapse navbar-collapse" id="topNavBar"></div>
		<ul class="nav navbar-nav">
			<li class="active">
				<a href="#">
					<span aria-hidden="true"></span>&nbsp; About Us
			</li>

		
		</ul>
	</div>
	
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/hospital/detail.html
{% extends 'hospital/base.html' %}
{% block body %}

<img src="#">

<h3>Name: </h3>
	<ul>
		 {{ item.name }}
	</ul>


<h3> Address: </h3>
	<ul>
		{{ item.street }} - {{ item.city }} - {{ item.state }} - {{ item.zipcode }}
	</ul>

<h3>Diagnosed area: </h3>
	<ul>
		{{ item.diagnosis_related_group }}
	</ul>

<h3>Covered charges: </h3>
	<ul>
		${{ item.avg_covered_charges }}
	</ul>

<h3>Total payments: </h3>
	<ul>
	${{ item.avg_total_payments }}
	</ul>
<h3>Medicare payments: </h3>
	<ul>
		${{ item.avg_medicare_payments }}
	</ul>

{% endblock %}

templates/hospital/index.html
{% extends 'hospital/base.html' %}

{% block body %}
{% if all_items %}
	<h3>Here are all the hospital:</h3>
	<ul>
		{% for item in all_items %}
		<li><a href="{% url 'hospital:detail' item.id %}">{{ item.name }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<h3>There is no hospital</h3>
{% endif %}
{% endblock %}